pipeline {
  agent none
  environment {
    DOCKER_IMAGE = null
  }
  stages {
    stage('Build') {
      agent {
          docker {
              image 'maven:3-alpine'
            // do some caching on maven here
              args '-v $HOME/.m2:/root/.m2'
          }
      }
      steps {
        sh 'mvn clean install'
      }
    }
    stage('dockerbuild') {
      steps {
        script {
          DOCKER_IMAGE = docker.build("consumer:latest")
        }
      }
    }
    stage('dockerrun') {
      steps {
        script {
   			try {	
				id = "consumer"
				docker.script.sh "docker stop ${id} && docker rm -f ${id}"
			} catch(e) {
	    		echo "container ${id} not found"
          	}
	        DOCKER_IMAGE.run('--name consumer -p 8181:8081')
        }
      }
    }
  }
}
